#! /bin/sh -eu
docker --version > /dev/null 2>&1 || { echo "Docker is required to run this script"; exit 1; }
docker run --rm --volume "$(pwd):/workspace" --workdir /workspace "$(docker build -q .)" python -m unittest discover -v
