name: Build and Test

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        #   - windows-latest    # GitHub Actions doesn't support Docker on Windows hosts
        #   -  macos-latest     # GitHub Actions doesn't support Docker on Mac hosts
    steps:
      - uses: actions/checkout@v5
      - name: Build and test
        run: |
          ./build-and-test
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
